# Generated by Django 5.2.6 on 2025-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0003_alter_gameroom_player1_alter_gameroom_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='task',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='GameRoom',
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
