# Generated by Django 5.2.6 on 2025-10-03 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player1_id',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player1_name',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player2_id',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player2_name',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='game_app.task'),
        ),
    ]
