# Generated by Django 6.0 on 2025-12-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tests',
            field=models.JSONField(default=0, help_text='Список тестов в формате [{input: [...], expected: ...}]'),
            preserve_default=False,
        ),
    ]
